% Auto-generates an index.html file and the demos.xml file for the example
% scripts, based on their numbering in the textbook.

filename = 'ListOfExamples.txt';
delimiter = '\t';
formatSpec = '%s%s%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);
fclose(fileID);
number = dataArray{:, 1};
label = dataArray{:, 2};
chaptitle = ["Numbers, problems, and algorithms"
    "Square linear systems"
    "Overdetermined linear systems"
    "Roots of nonlinear equations"
    "Piecewise interpolation"
    "Initial-value problems"
    "Matrix analysis"
    "Krylov methods in linear algebra"
    "Global function approximation"
    "Boundary-value problems"
    "Diffusion equations"
    "Advection equations"
    "Two-dimensional problems"
    ];

%% examples.html
fid = fopen('examples.html','w');
fprintf(fid,'<head><title>FNC Examples</title></head>\n');
fprintf(fid,'<body>\n');
fprintf(fid,'<p>These are examples from the text <i>Fundamentals of Numerical Computation</i>, by Driscoll and Braun, 1st edition (2017).</p>\n');
fprintf(fid,'<p>For live links to the codes, view this page in the MATLAB web browser.</p>\n');
k = 1;
for i = 1:13
    fprintf(fid,'<h3><a name="%i">Chapter %i:</a> %s</h3>\n',i,i,chaptitle(i));
    fprintf(fid,'\t<ul>\n');
    while k <= length(label)
        chap = sscanf(number(k),'%i.',1);
        if chap > i, break, end
        fprintf(fid,'\t\t<li><a href="chapter%02d/html/%s.html">%s</a>',i,label(k),number(k));
        fprintf(fid,'\n\t\t\t (<a href="matlab:edit(''chapter%02d/%s'')">view code</a>)</li>\n',i,label(k));
        k = k+1;
    end
    fprintf(fid,'\t</ul>\n');
end
fprintf(fid,'</body>\n');
fclose(fid);

%% demos.xml
fid = fopen('../demos.xml','w');
fprintf(fid,'<?xml version="1.0" encoding="utf-8"?>\n<demos>\n');
fprintf(fid,'<name>Fundamentals of Numerical Computation</name>\n');
fprintf(fid,'<type>toolbox</type>\n');
fprintf(fid,'<icon>HelpIcon.DEMOS</icon>\n<website/>\n');
fprintf(fid,'<description>Examples that appear in the textbook Fundamentals of Numerical Computation, 1st edition (2018).</description>\n');
k = 1;
for i = 1:13
    % At this writing, the demos.xml file does not seem to support files
    % generated by an mlx script. So the type is 'other'. 
    fprintf(fid,'<demosection><label>Chapter %d: %s</label>\n',i,chaptitle(i));
    while k <= length(label)
        chap = sscanf(number(k),'%i.',1);
        if chap > i, break, end
        fprintf(fid,'\t<demoitem>\n\t\t<label>%s</label>\n',number(k));
        fprintf(fid,'\t\t<type>other</type>\n\t\t<source>%s</source>\n',label(k));
        fprintf(fid,'\t\t<file>examples/chapter%02d/html/%s.html</file>\n',i,label(k));
        fprintf(fid,'\t</demoitem>\n');
        k = k+1;
    end
    fprintf(fid,'</demosection>\n');
end
fprintf(fid,'</demos>\n');
fclose(fid);
